In [2]:
# 使用sklearn.preprocessing.scale()函数，将给定数据进行标准化
from sklearn import preprocessing
import numpy as np
X = np.array([[ 1.3, -1.6,  2.8],
              [ 2.5,  0.6,  0.9],
              [ 0.6,  1.7, -1.3]])
X_scaled = preprocessing.scale(X)
 
X_scaled  

array([[-0.21242964, -1.33630621,  1.19380825],
       [ 1.31706379,  0.26726124,  0.05969041],
       [-1.10463415,  1.06904497, -1.25349867]])

In [3]:
# 处理后数据的均值
X_scaled.mean(axis=0)

array([ 7.40148683e-17, -7.40148683e-17,  7.40148683e-17])

In [4]:
# 处理后数据的方差
X_scaled.std(axis=0)

array([1., 1., 1.])

In [5]:
# sklearn.preprocessing.StandardScaler类
scaler=preprocessing.StandardScaler().fit(X)
scaler

StandardScaler(copy=True, with_mean=True, with_std=True)

In [6]:
# scaler.transform()
new_X=np.array([[2.4, -1.5, 2.8],
                [2.7, -0.9, 0],
                [0.9, -1.9, -1]])
scaler.transform(new_X)

array([[ 1.18960601, -1.26341678,  1.19380825],
       [ 1.57197937, -0.8260802 , -0.4775233 ],
       [-0.72226079, -1.5549745 , -1.07442743]])

In [7]:
# MinMaxScaler
min_max_scaler = preprocessing.MinMaxScaler()
X_minmax=min_max_scaler.fit_transform(X)
X_minmax

array([[0.36842105, 0.        , 1.        ],
       [1.        , 0.66666667, 0.53658537],
       [0.        , 1.        , 0.        ]])

In [8]:
# min_max_scaler.transform()
X_test = np.array([[-3., -1.,  4.]])
X_test_minmax = min_max_scaler.transform(X_test)
X_test_minmax

array([[-1.89473684,  0.18181818,  1.29268293]])

In [9]:
# Normalizer
X_normalized = preprocessing.normalize(X, norm='l2')
X_normalized

array([[ 0.37387825, -0.46015785,  0.80527623],
       [ 0.91777887,  0.22026693,  0.33040039],
       [ 0.26995276,  0.76486616, -0.58489765]])

In [10]:
normalizer = preprocessing.Normalizer().fit(X)
normalizer

Normalizer(copy=True, norm='l2')

In [11]:
# normalizer.transform
normalizer.transform([[-1, -1, 0]])

array([[-0.70710678, -0.70710678,  0.        ]])

In [12]:
# Binarizer
binarizer = preprocessing.Binarizer().fit(X)
binarizer.transform(X)

array([[1., 0., 1.],
       [1., 1., 1.],
       [1., 1., 0.]])

In [13]:
# change the threshold
binarizer = preprocessing.Binarizer(threshold=1.1)
binarizer.transform(X)

array([[1., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [14]:
# Encoding categorical features
# OneHotEncode
enc = preprocessing.OneHotEncoder()
enc.fit([[0, 0, 3], [1, 1, 0], [0, 2, 1], [1, 0, 2]])
enc.transform([[0,2,1]]).toarray()

array([[1., 0., 0., 0., 1., 0., 1., 0., 0.]])

In [15]:
# LabelEncoder
le = preprocessing.LabelEncoder()
le.fit([2, 4, 6, 8])
le.transform([4, 8, 2, 6])

array([1, 3, 0, 2], dtype=int64)

In [16]:
# OrdinalEncoder
enc = preprocessing.OrdinalEncoder()
x = [['Male', 1], ['Female', 3], ['Female', 2]]
enc.fit(x)
enc.transform([['Female', 3], ['Male', 1]])

AttributeError: module 'sklearn.preprocessing' has no attribute 'OrdinalEncoder'

In [48]:
# 缺失值处理
import numpy as np
from sklearn.preprocessing import Imputer

imp = Imputer(missing_values='NaN', strategy='mean', axis=0)
imp.fit([[1, 3], [np.nan, 4], [1, 4]])

X = [[np.nan, 3], [6, np.nan], [1, 4]]
imp.transform(X)

array([[1.        , 3.        ],
       [6.        , 3.66666667],
       [1.        , 4.        ]])

In [49]:
# Generating polynomial features
import numpy as np
from sklearn.preprocessing import PolynomialFeatures
X = np.arange(6).reshape(3, 2)
poly = PolynomialFeatures(2)
poly.fit_transform(X)

array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [51]:
# custom transformers
import numpy as np
from sklearn.preprocessing import FunctionTransformer

transformer = FunctionTransformer(np.log1p)

X = np.arange(6).reshape(3,2)
transformer.transform(X)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947]])

In [1]:
# Discretization
import numpy as np
from sklearn.preprocessing import KBinsDiscretizer
est = KBinsDiscretizer()
X = np.arange(6).reshape(3,2)
print(X)
est.fit_transform(X).toarray()

ImportError: cannot import name 'KBinsDiscretizer' from 'sklearn.preprocessing' (C:\Users\saisai\Anaconda3\lib\site-packages\sklearn\preprocessing\__init__.py)

In [61]:
from sklearn import preprocessing
import numpy as np
a = preprocessing.OneHotEncoder()
b = preprocessing.LabelEncoder()

temp = b.fit_transform([123,456,789])
print(temp) 
# 输出LabelEncoder的结果
temp = temp.reshape(-1,1)
a.fit(temp) 
#将LabelEncoder的结果作为OneHotEncoder特征输入
a = a.transform(b.transform([123,789]).reshape(-1, 1))
print(a)

[0 1 2]
  (0, 0)	1.0
  (1, 2)	1.0
